add_newline = false
format = """
$character$directory$git_branch$git_status ${custom.separator}"""
right_format = """${custom.swift}"""

[character]
error_symbol = "[􀇿 ](bold fg:#FFCC00)"
success_symbol = "[􀒆 ](bold)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold"
truncate_to_repo = false
truncation_length = 2

[git_branch]
format = " at [$branch(:$remote_branch)]($style)"
style = "bold"
truncation_length = 20

[git_status]
ahead = "(􀄨 ${count})"
behind = "(􀄩 ${count})"
diverged = "(􀄨 ${ahead_count}, 􀄩 ${behind_count})"
format = "[(([,]() $ahead_behind))]($style)"
staged = "􀈸 "
stashed = ""
style = "bold"
untracked = "􀈷 "

[swift]
disabled = true

[custom.separator]
command = "prompt_separator"
description = "A custom separator, indicating the style of the repo"
format = "[($output  )]($style)"
style = "bold"
when = true

[custom.swift]
description = "Current directory contains a Swift Project"
detect_extensions = ["swift", "xcodeproj"]
format = " [$symbol]($style)"
style = "fg:#bf5700"
symbol = "􀫊 "
when = "[ -n \"$(find . -maxdepth 1 -type d -name '*.xcodeproj' 2>/dev/null)\" ] || exit 1"
