update

install axel
install coreutils
install gifsicle
install git
install go
install imagemagick
install pngcrush
install wget
install zsh
install zsh-completions

# cask
tap caskroom/cask
install brew-cask

# quicklook plugins
cask install qlcolorcode
cask install qlstephen
cask install qlmarkdown
cask install quicklook-json
cask install qlprettypatch
cask install quicklook-csv
cask install betterzipql
cask install webp-quicklook
