#!/bin/sh
set -e

echo "- Setting up iTerm"

defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/iterm2"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -int 1

echo "- Linking iTerm Profiles directory"

mkdir -p "~/Library/Application Support/iTerm2/"
rm -rf "~/Library/Application Support/iTerm2/DynamicProfiles"

ln -sfhF ~/.dotfiles/iterm2/profiles ~/Library/Application\ Support/iTerm2/DynamicProfiles
