#!/bin/sh
set -e

echo "- Setting up iTerm"

defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/iterm2"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -int 1

echo "- Linking iTerm Profiles directory"

mkdir -p "$HOME/Library/Application Support/iTerm2/"
rm -rf "$HOME/Library/Application Support/iTerm2/DynamicProfiles"

ln -sfhF "$HOME/.dotfiles/iterm2/profiles" "$HOME/Library/Application Support/iTerm2/DynamicProfiles"
